=== nashidau/rmnebula/XML/spelllist/spelllist.dtd
<!--
        Rolemaster Spell list DTD class

        This was originally written by Brett Nash <nash@nash.nu>

        More information, and the most recent version of this document
        can be found at:
                http://www.nash.nu/Rolemaster/XML/spelllist

        Copyright 2002-2003 Brett Nash, Bent Dalager, Thomas Neumann 

        Changes 
        * Version 1.1
            - Fairly major changes from Thomas Neumann; should not break
                compatibility with any existing lists however
            - Added new 'spellbook' element.  
            - Added new 'spellgroup' element.
                A spellbook contains a number of spellgroups.  A spellgroup
                        contains a number of spelllists.  
        * Version 1.0.3
            - Added <ref> to description tags (references to other
                spell lists
            - Allowed multiple spell descriptions.
        * Version 1.0.2
            - Added <annotation> after descriptions
            - Added <rrmod> 
        * Version 1.0.1
            - No changes
-->

<!-- Optional top level element.  This is used by PCs to indicate all the
        spells they know, otherwise it can be used to store all available
        spellists or similar -->
<!ELEMENT spellbook (spellgroup*)>

<!-- spellgroup
        A group of related spells, which share the same realm and type
        (base, open, closed etc).
        Valid realms are 'essence', 'channeling' and 'mentalism'.
        Valid types are 'base', 'open', 'closed' and 'trainingpackage'
        If the type is 'base', the profession attribute is required.
                it is a valid RM profession name
-->
<!ELEMENT spellgroup (spelllist*)>
<!ATTLIST spellgroup realm CDATA #REQUIRED>
<!ATTLIST spellgroup type CDATA #REQUIRED>
<!ATTLIST spellgroup ref CDATA #OPTIONAL>



<!-- Top level element - spelllist.
        This contains the name of the spell list, various optional
        pieces of meta-data, and the list of spells themselves
-->
<!ELEMENT spelllist (name,
                     listtype,
                     id?,
                     author*,
                     description*,
                     spell+,
                     notes?)>

<!-- The spelllist (or spell name).  A simple string... -->
<!ELEMENT name (#PCDATA)>

<!-- What type of spelllist it is - for instance a Enchanter Base, or
        Closed Essence. -->
<!ELEMENT listtype (#PCDATA)>

<!-- id is the spellist id number if it is a RMSS list
        This tag is not used in other lists currently -->
<!ELEMENT id (#PCDATA)>

<!-- author is a list of people who wrote the list, or hold the copyright
        for the list.  For multiple authors use multiple tags -->
<!ELEMENT author (#PCDATA)>

<!--  description is a short description of the list.  Most lists won't
        use this field. -->
<!ELEMENT description (#PCDATA | ref )*>

<!-- spell entries themselves.  Spells are listed in order from 
        lowest to highest level.  if there are multiple spells of
        the same order they can be listed in any order.
-->
<!ELEMENT spell (level,
                 name,
                 areaofeffect?,
                 duration?,
                 range?,
                 type,
                 description+,
                 annotation?,
                 nopp?,
                 instantaneous?,
                 rrmod?)>
<!-- Level - the level of the spell 
        Should be one of 1-20, 25, 30, 50 -->
<!ELEMENT level (#PCDATA)>

<!-- Spell name (same as spelllistname) -->

<!ELEMENT areaofeffect (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT range (#PCDATA)>

<!-- Spell type - F, P, I, U, E (DE BE), 
        subtypes, optional (lower case following) one of s or m -->
<!ELEMENT type (#PCDATA)>

<!-- Any special notes for the spell - that which is not appropriate for the
normal descritpion. -->
<!ELEMENT annotation (#PCDATA)>

<!ELEMENT nopp EMPTY>
<!ELEMENT instantaneous EMPTY>

<!-- An interger bonus or penalty pplied to RRs for the spell -->
<!ELEMENT rrmod (#PCDATA)>


<!-- A reference to a spell somewhere else on the list -->
<!ELEMENT ref (#PCDATA)>


<!ELEMENT notes (note+)>
<!ELEMENT note (#PCDATA)>

=== nashidau/rmnebula/XML/spelllist/examples/mind_visions.xml
<?xml version='1.0'?>

<!DOCTYPE spelllist SYSTEM "spelllist.dtd">

<spelllist>
        <name>Mind Visions</name>
        <listtype>Seer Base List</listtype>
        <author>I.C.E</author>
        <spell>
                <level>1</level>
                <name>Origins</name>
                <areaofeffect>1 object</areaofeffect>
                <duration>-</duration>
                <range>touch</range>
                <type>I</type>
                <description>
                   Gives a general idea of the place of origin of an item.
                </description>
        </spell>
        <spell>
                <level>2</level>
                <name>Detect Curse</name>
                <areaofeffect>varies</areaofeffect>
                <duration>-</duration>
                <range>touch</range>
                <type>I</type>
                <description>
                   Detects if a curse is upon a person, place or object.
                </description>
        </spell>
        <spell>
                <level>3</level>
                <name>Vision Behind I</name>
                <areaofeffect>varies</areaofeffect>
                <duration>varies</duration>
                <range>touch</range>
                <type>I</type>
                <description>
                   Caster gets a vision of up to 1 minute per level into the
                   past. The caster must select the point in the past to be
                   viewed (and the vision will be accurate within one
                   minute). The vision must be associated with a person,
                   place, or object touched at the time of casting. The
                   vision includes sight and sound. The vision will last up
                   to 1 round per level if the caster concentrates and
                   remains inactive. Time passes at a rate of one round of
                   real time for 10 rounds of vision.
                </description>
        </spell>
        <spell>
                <level>4</level>
                <name>Power Lore</name>
                <areaofeffect>1 item</areaofeffect>
                <duration>-</duration>
                <range>touch</range>
                <type>I</type>
                <description>
                   Gives the origin of an item's power.
                </description>
        </spell>
        <spell>
                <level>5</level>
                <name>Vision Guide</name>
                <areaofeffect>1 spell</areaofeffect>
                <duration>varies</duration>
                <range>self</range>
                <type>I</type>
                <description>
                   This spell gives the caster the ability to scan the past
                   by "feeling the temporal location for significant
                   events". This translates to the caster knowing the
                   approximate time-frames of significant events, without
                   knowing the nature of the events. If the caster casts a
                   Vision Behind spells within one minute of casting this
                   spell, she will be able to see the specific events.
                </description>
        </spell>
        <spell>
                <level>6</level>
                <name>Item Vision</name>
                <areaofeffect>1 item</areaofeffect>
                <duration>varies</duration>
                <range>touch</range>
                <type>I</type>
                <description>
                   Gives a vision of a significant event in the item's past.
                </description>
        </spell>
        <spell>
                <level>7</level>
                <name>Vision Behind II</name>
                <areaofeffect>varies</areaofeffect>
                <duration>varies</duration>
                <range>touch</range>
                <type>I</type>
                <description>
                   As Vision Behind I, except time range is up to 10 minutes
                   per level (with an accuracy of +5 minutes) and the trance
                   can last up to 1 minute per level.
                </description>
        </spell>
        <spell>
                <level>8</level>
                <name>Vision Enhancement</name>
                <areaofeffect>1 spell</areaofeffect>
                <duration>varies</duration>
                <range>self</range>
                <type>I</type>
                <description>
                   When cast before a Vision Behind spell, this allows the
                   caster to perceive the past using one (and only one)
                   additional sense, or to use one and only one perceptive
                   skill (in addition to the normal vision and hearing).
                </description>
        </spell>
        <spell>
                <level>9</level>
                <name>Vision Behind III</name>
                <areaofeffect>varies</areaofeffect>
                <duration>varies</duration>
                <range>touch</range>
                <type>I</type>
                <description>
                   As Vision Behind I, except time range is up to 1 hour per
                   level (with an accuracy of +30 minutes) and the trance
                   can last up to 5 minute per level.
                </description>
        </spell>
        <spell>
                <level>10</level>
                <name>Delving</name>
                <areaofeffect>1 item</areaofeffect>
                <duration>-</duration>
                <range>touch</range>
                <type>I</type>
                <description>
                   Gives significant details about an item's construction
                   and purpose (not specific powers).
                </description>
        </spell>
</spelllist>
