=== nashidau/rmnebula/nebula/nebula/characters/rmsscharacter.dtd
<!-- 
        The RMSS character class
-->



<!-- Top level: the chracter itself -->
<!ELEMENT rmsscharacter (data,
                        stats,
                        skills,
                        rrs,
                        items?,
                        other?)>
<!ATTLIST rmsscharacter id      CDATA   #IMPLIED
                        version NMTOKEN #REQUIRED>
<!-- Note that id must be unique,
        and vrsion must be 0.2 -->

<!-- **** -->
<!-- Data -->
<!-- **** -->
<!-- Generic character data -->
<!ELEMENT data (name,
                player,
                campaign?,
                fixed,
                experience,
                raceinfo,
                appearance,
                role,
                background)>
<!ELEMENT name (#PCDATA)>

<!-- Inoformation about the player of the character -->
<!ELEMENT player (name,email?,application)>
<!ELEMENT email (#PCDATA)>  <!-- Optional email address -->
<!ELEMENT application (#PCDATA)> <!-- The application that created the 
                                        character -->

<!ELEMENT campaign (name,gm*,genre?)>
<!ELEMENT gm (#PCDATA)>  <!-- Who _normally_ gms this character -->
<!ELEMENT genre (#PCDATA)> <!-- the genre file for hte skillset -->

<!ELEMENT fixed (race,
                 profession,
                 trainingpackages?,
                 realm,
                 type)>
<!ELEMENT race (#PCDATA)>   <!-- eg Common Man - Urban -->
<!ELEMENT profession (#PCDATA)> <!-- eg Zen Monk -->
<!ELEMENT trainingpackages (tp*)> <!-- a list of all TPs -->
<!ELEMENT realm (#PCDATA)> <!-- What realm - includes casting method for
                                        Essence users -->
<!ELEMENT type (#PCDATA)> <!-- Non, semi, pure, hybrid - FIXME: should make
                                this one of the specific values -->
<!ELEMENT tp (#PCDATA)>  <!-- an individual tp -->

<!ELEMENT experience (level,dp?,dpspent?,experiencepoints)> 
<!ELEMENT level (#PCDATA)> <!-- natural numbers only -->
<!ELEMENT dp (#PCDATA)> <!-- used for continual development -->
<!ELEMENT dpspent (#PCDATA)>
<!ELEMENT experiencepoints (#PCDATA)> 

<!ELEMENT raceinfo (exhaustionbonus,
                        lifespan,
                        souldeparture,
                        recoverymultiplier,
                        racetype,
                        startinglanguages,
                        backgroundpoints,
                        bodydevelopment,
                        arcane,
                        channeling,
                        essence,
                        mentalism)>
<!ELEMENT exhaustionbonus (#PCDATA)>
<!ELEMENT lifespan (#PCDATA)>
<!ELEMENT souldeparture (#PCDATA)>
<!ELEMENT recoverymultiplier (#PCDATA)>
<!ELEMENT racetype (#PCDATA)>
<!ELEMENT startinglanguages (#PCDATA)>
<!ELEMENT backgroundpoints (#PCDATA)>
<!ELEMENT bodydevelopment (#PCDATA)>
<!ELEMENT arcane (#PCDATA)>
<!ELEMENT channeling (#PCDATA)>
<!ELEMENT essence (#PCDATA)>
<!ELEMENT mentalism (#PCDATA)>


<!ELEMENT appearance (skin,age,sex,height,weight,eyes,hair)>
<!ELEMENT skin (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT eyes (#PCDATA)>
<!ELEMENT hair (#PCDATA)>

<!ELEMENT role (personality,motivations,alignment)>
<!ELEMENT personality (#PCDATA)>
<!ELEMENT motivations (#PCDATA)>
<!ELEMENT alignment (#PCDATA)>

<!ELEMENT background (nationality,
                      hometown,
                      religon,
                      lord?,
                      parents,
                      spouse?,
                      children?,
                      mentor?,
                      patron?)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT hometown (#PCDATA)>
<!ELEMENT religon (#PCDATA)>
<!ELEMENT lord (#PCDATA)>
<!ELEMENT parents (father?,mother?)>
<!ELEMENT father (#PCDATA)>
<!ELEMENT mother (#PCDATA)>
<!ELEMENT spouse (#PCDATA)>
<!ELEMENT children (name*)>
<!ELEMENT mentor (#PCDATA)>
<!ELEMENT patron (#PCDATA)>

<!-- ***** -->
<!-- Stats -->
<!-- ***** -->
<!ELEMENT stats (stat+)>
<!ELEMENT stat (name, abbr, temp, potential,basic,racial,
                special, total, primestat?, realmstat?)>
<!-- name is PCDATA as usual -->
<!ELEMENT abbr (#PCDATA)>
<!ELEMENT temp (#PCDATA)>
<!ELEMENT potential (#PCDATA)>
<!ELEMENT basic (#PCDATA)>
<!ELEMENT racial (#PCDATA)>
<!ELEMENT special (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT primestat EMPTY>
<!ELEMENT realmstat EMPTY>

<!-- ****** -->
<!-- Skills -->
<!-- ****** -->
<!ELEMENT skills (category+)>
<!-- categories -->
<!ELEMENT category (name,
                    statbonuses,
                    progression,
                    cost,
                    professionbonus,
                    statbonus,
                    specialbonus,
                    ranks,
                    rankbonus,
                    total,
                    hidden?,
                    halfrank?,
                    (skill|skillgroup)+)>
<!ELEMENT rankbonus (#PCDATA)>
<!ELEMENT categorybonus (#PCDATA)>
<!ELEMENT statbonuses (#PCDATA)>
<!ELEMENT progression (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT professionbonus (#PCDATA)>
<!ELEMENT statbonus (#PCDATA)>
<!ELEMENT specialbonus (#PCDATA)>
<!ELEMENT hidden EMPTY>
<!ELEMENT halfrank EMPTY>

<!-- skillgroup -->
<!ELEMENT skillgroup (name,class?,specialbonus?,hidden?,skill*)>

<!-- skills -->
<!ELEMENT skill (name,
                class?,
                specialbonus?,
                ranks,
                rankbonus,
                categorybonus,
                total,
                hidden?,
                halfrank?)>
<!ELEMENT ranks (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT itembonus (#PCDATA)>

<!-- Resisteance Rolls -->
<!ELEMENT rrs (rr+)>
<!ELEMENT rr (name,statbonuses?,statbonus?,racialbonus,specialbonus,totalbonus)>

<!ELEMENT racialbonus (#PCDATA)>
<!ELEMENT totalbonus (#PCDATA)>

<!ELEMENT items EMPTY>
<!-- currently undefined -->
<!ELEMENT other EMPTY>

=== nashidau/rmnebula/nebula/nebula/characters/Evant.xml
<?xml version='1.0'?>
<?xml-stylesheet type="text/css" href="rmsscharacter.css"?>
<!DOCTYPE rmsscharacter SYSTEM "rmsscharacter.dtd">

<rmsscharacter id="neb-0001" version="0.2">

<data>
        <name>Evant</name>
        <player>
                <name>Nash</name>
                <email>nash@nash.nu</email>
                <application>Nebula</application>
        </player>
        <campaign>
                <name>Cheevers</name>
                <gm>Denzil</gm>
                <genre>Denzil</genre>
        </campaign>
        <fixed>
                <race>Common-Man (Urban)</race>
                <profession>Runemage - Essence</profession>
                <trainingpackages>
                        <tp>Spell Researcher</tp>
                        <tp>Amateur Mage (Revised)</tp>
                </trainingpackages>
                <realm>Essence - Nomenist</realm>
        </fixed>
        <experience>
                <level>4</level>
                <dp>0</dp> <!-- for continual dev people -->
                <dpspent>0</dpspent>
                <experiencepoints>40000</experiencepoints>
        </experience>
        <raceinfo>
                <souldepart>12</souldepart>
                <recoverymultiplier>1</recoverymultiplier>
                <!-- BD and PP in relevant skills -->
        </raceinfo>
        <appearance>
                <!-- I have appearance as a stat normally?
                        Agree? -->
                
                <skin>Fair - slightly tanned</skin>
                <age>22</age>
                <sex>Male</sex>
                <height>5'8"</height>
                <weight>150 lbs</weight>
                <eyes>Green</eyes>
                <hair>Brown</hair>
        </appearance>
        <role> <!-- Not sure about these - maybe they belong somewhere
        else... -->
                <personality> </personality>
                <motivations> </motivations>
                <alignment>   </alignment>
        </role>
        <background>
                <nationality>Chee Freel</nationality>
                <hometown>Cheevers</hometown>
                <religon>Gilean</religon>
                <lord></lord>
                <parents>
                        <father></father> <!-- xlink to parents -->
                        <mother></mother>
                </parents>
                <spouse></spouse>
                <children>
                        <name></name>  <!-- xlink to child :) -->
                </children>
                <mentor>Rotando</mentor>
              <patron></patron>
        </background>
</data>
<defense>
        <defensive>
                <armortype>1</armortype>
        <!--
                <defensivebonus>
                        <quicknesspenalty>0</quicknesspenalty>
                        <quicknessbonus>0</quicknessbonus>
                        <adrenaldefense>0</adrenaldefense>
                        <shieldbonus>0</shieldbonus>
                        <specialbonus>0</specialbonus>
                        <totaldefensivebonus>0</totaldefensivebonus>
                </defensivebonus>
        -->
        </defensive>
        <resistances>
                <rr>
                        <name>Channeling</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>3</statbonus>
                        <totalbonus>3</totalbonus>
                </rr>
                <rr>
                        <name>Essence</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>45</statbonus>
                        <totalbonus>45</totalbonus>
                </rr>
                <rr>
                        <name>Mentalism</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>3</statbonus>
                        <totalbonus>3</totalbonus>
                </rr>
                <rr>
                        <name>Chan/Ess</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>16</statbonus>
                        <totalbonus>16</totalbonus>
                </rr>
                <rr>
                        <name>Chan/Ment</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>2</statbonus>
                        <totalbonus>45</totalbonus>
                </rr>
                <rr>
                        <name>Ess/Ment</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>16</statbonus>
                        <totalbonus>16</totalbonus>
                </rr>
                <rr>
                        <name>Arcane</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>17</statbonus>
                        <totalbonus>17</totalbonus>
                </rr>
                <rr>
                        <name>Poison</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>9</statbonus>
                        <totalbonus>9</totalbonus>
                </rr>
                <rr>
                        <name>Disease</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>9</statbonus>
                        <totalbonus>9</totalbonus>
                </rr>
                <rr>
                        <name>Fear</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>24</statbonus>
                        <totalbonus>24</totalbonus>
                </rr>
                <rr>
                        <name>Fear</name>
                        <racialbonus>0</racialbonus>
                        <specialbonus>0</specialbonus>
                        <statbonus>24</statbonus>
                        <totalbonus>24</totalbonus>
                </rr>
                <!-- Heat / Cold???? -->
        </resistances>
</defense>

<points>
        <hits>
        </hits>
        <powerpoints>
        </powerpoints>
        <exhaustionpoints>
        </exhaustionpoints>
</points>

<maneuver>
        <!-- FIXME -->
</maneuver>

<stats>
        <stat>
                <name>Agility</name>
                <abbr>Ag</abbr>
                <temp>62</temp>
                <potential>81</potential>
                <basic>0</basic>
                <racial>0</racial>
                <special>0</special>
                <total>0</total>
        </stat>
        <stat>
                <name>Constitution</name>
                <abbr>Co</abbr>
                <temp>82</temp>
                <potential>91</potential>
                <basic>3</basic>
                <racial>0</racial>
                <special>0</special>
                <total>0</total>
        </stat>
        <stat>
                <name>Memory</name>
                <abbr>Me</abbr>
                <temp>88</temp>
                <potential>88</potential>
                <basic>4</basic>
                <racial>0</racial>
                <special>0</special>
                <total>4</total>
        </stat>
        <stat>
                <name>Reasoning</name>
                <abbr>Re</abbr>
                <temp>95</temp>
                <potential>95</potential>
                <basic>7</basic>
                <racial>0</racial>
                <special>0</special>
                <total>7</total>
                <primestat />
        </stat>
        <stat>
                <name>Self Discipline</name>
                <abbr>SD</abbr>
                <temp>93</temp>
                <potential>94</potential>
                <basic>6</basic>
                <racial>2</racial>
                <special>0</special>
                <total>8</total>
        </stat>
        <stat>
                <name>Empathy</name>
                <abbr>Em</abbr>
                <temp>94</temp>
                <potential>94</potential>
                <basic>7</basic>
                <racial>0</racial>
                <special>8</special>
                <total>15</total>
                <primestat />
                <realmstat></realmstat>
        </stat>
        <stat>
                <name>Intuition</name>
                <abbr>In</abbr>
                <temp>74</temp>
                <potential>79</potential>
                <basic>1</basic>
                <racial>0</racial>
                <special>0</special>
                <total>1</total>
        </stat>
        <stat>
                <name>Presence</name>
                <abbr>Pr</abbr>
                <temp>72</temp>
                <potential>79</potential>
                <basic>1</basic>
                <racial>0</racial>
                <special>0</special>
                <total>1</total>
        </stat>
        <stat>
                <name>Quickness</name>
                <abbr>Qu</abbr>
                <temp>58</temp>
                <potential>65</potential>
                <basic>0</basic>
                <racial>0</racial>
                <special>0</special>
                <total>0</total>
        </stat>
        <stat>
                <name>Strength</name>
                <abbr>St</abbr>
                <temp>58</temp>
                <potential>65</potential>
                <basic>0</basic>
                <racial>2</racial>
                <special>0</special>
                <total>0</total>
        </stat>
</stats>

<skills>

	<category>
