=== nashidau/rmnebula/nebula/nebula/data/spelllists/spelllist.dtd
<!--
        Rolemaster Spell list DTD class

        This was originally written by Brett Nash <nash@nash.nu>

        More information, and the most recent version of this document
        can be found at:
                http://www.nash.nu/Rolemaster/

        Copyright 2002 Brett Nash
-->

<!-- Top level element - spelllist.
        This contains the name of the spell list, various optional
        pieces of meta-data, and the list of spells themselves
-->
<!ELEMENT spelllist (name,
                     listtype,
                     id?,
                     author*,
                     description?,
                     spell+,
                     notes?)>

<!-- The spelllist (or spell name).  A simple string... -->
<!ELEMENT name (#PCDATA)>

<!-- What type of spelllist it is - for instance a Enchanter Base, or
        Closed Essence. -->
<!ELEMENT listtype (#PCDATA)>

<!-- id is the spellist id number if it is a RMSS list
        This tag is not used in other lists currently -->
<!ELEMENT id (#PCDATA)>

<!-- author is a list of people who wrote the list, or hold the copyright
        for the list.  For multiple authors use multiple tags -->
<!ELEMENT author (#PCDATA)>

<!--  description is a short description of the list.  Most lists won't
        use this field. -->
<!ELEMENT description (#PCDATA)>

<!-- spell entries themselves.  Spells are listed in order from 
        lowest to highest level.  if there are multiple spells of
        the same order they can be listed in any order.
-->
<!ELEMENT spell (level,
                 name,
                 areaofeffect?,
                 duration?,
                 range?,
                 type,
                 description,
                 nopp?,
                 instantaneous?)>
<!-- Level - the level of the spell 
        Should be one of 1-20, 25, 30, 50 -->
<!ELEMENT level (#PCDATA)>

<!-- Spell name (same as spelllistname) -->

<!ELEMENT areaofeffect (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT range (#PCDATA)>

<!-- Spell type - F, P, I, U, E (DE BE), 
        subtypes, optional (lower case following) one of s or m -->
<!ELEMENT type (#PCDATA)>

<!ELEMENT nopp EMPTY>
<!ELEMENT instantaneous EMPTY>


<!ELEMENT notes (note+)>
<!ELEMENT note (#PCDATA)>

=== nashidau/rmnebula/nebula/nebula/data/base/stardust.xml
<?xml version='1.0'?>

<!DOCTYPE spelllist SYSTEM
        "/home/nash/work/rolemaster/XML/spelllist/spelllist.dtd">


<spelllist>
    <name>Spell list</name>
    <listtype></listtype>
    <author>Brett Nash</author>
    <spell>
        <level>1</level>
        <name>Spell 1</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description> 
    </spell>
    <spell>
        <level>2</level>
        <name>Spell 2</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>3</level>
        <name>Spell 3</name>
        <areaofeffect></areaofeffect>
        <duration></duration> 
        <range></range> 
        <type></type> 
        <description></description>
    </spell>
    <spell>
        <level>4</level>
        <name>Spell 4</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>5</level>
        <name>Spell 5</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>6</level>
        <name>Spell 6</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>7</level>
        <name>Spell 7</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>8</level>
        <name>Spell 8</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>9</level>
        <name>Spell 9</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>10</level>
        <name>Spell 10</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell> 
        <level>11</level> 
        <name>Spell 11</name>
        <areaofeffect></areaofeffect>
        <duration></duration> 
        <range></range>
        <type></type>
        <description></description> 
    </spell>
    <spell>
        <level>12</level>
        <name>Spell 12</name>
        <duration></duration> 
        <range></range> 
        <type></type> 
        <description></description>
    </spell>
    <spell>
        <level>13</level>
        <name>Spell 13</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>14</level>
        <name>Spell 14</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>15</level>
        <name>Spell 15</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>16</level>
        <name>Spell 16</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>17</level>
        <name>Spell 17</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>18</level>
        <name>Spell 18</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>19</level>
        <name>Spell 19</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>20</level>
        <name>Spell 20</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>25</level>
        <name>Spell 25</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell> 
        <level>30</level>
        <name>Spell 30</name>
        <areaofeffect></areaofeffect> 
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
    <spell>
        <level>50</level>
        <name>Spell 50</name>
        <areaofeffect></areaofeffect>
        <duration></duration>
        <range></range>
        <type></type>
        <description></description>
    </spell>
</spelllist>

=== nashidau/rmnebula/nebula/nebula/data/spelllists/seeming_memories.xml
<?xml version='1.0'?>

<!DOCTYPE spelllist SYSTEM "spelllist.dtd">

<spelllist>
        <name>Seeming Memories</name>
        <listtype>Enchanter Base</listtype>
        <author>I.C.E</author>
        <spell>
                <level>1</level>
                <name>Relive Experience</name>
                <areaofeffect>1 target</areaofeffect>
                <duration>1 rnd/5 fail</duration>
                <range>100'</range>
                <type>Fm</type>
                <description>
                   The caster causes the target to relive an experience
                   chosen by the caster at the of casting.  If the target is
                   in a relaxed state of mind, the target will be in a
                   reverie and obvlivious to his surroundigs unless
                   disturbed (loud noise, physical prod, etc).  If the
                   target is active, the target will remain active but be
                   distracted by momentary flashbacks and the attempts of
                   his mind to relate the exxperience to the current
                   situation (-20 to all actions).  This spell will also
                   provide the target with a +25 bonus to recalling specific
                   details of the remembered experience.  This bonus is not
                   cumulative with Force Recall or Recall spells.
                </description>
        </spell>
        <spell>
                <level>2</level>
                <name>Memory Cue</name>
                <areaofeffect>1 target</areaofeffect>
                <range>100'</range>
                <type>Fm</type>
                <description>The caster can select a topic and obtain one
                cue per level of the caster from the target.  Each cue will
                relate to an experience of the target with respect to the
                topic.  These cues are used as the triggers for the Relive
                or and Share Experience Spells
                </description>
        </spell>
</spelllist>
