=== nashidau/rmnebula/XML/rmssrace/rmssrace.dtd
<!--

        rmssrace

        DTD for Rolemaster cultures/races.

-->

<!-- The top level element 
        rmssrace is the prefered, race is acceptable-->
<!ELEMENT rmssrace (data,stats?,rrs,skills)>

<!-- The racial stat bonuses
        The field is optional -
        If is in place it must contain at least one stat bonus
        The possible abbriviations are:
                Ag,Co,Me,Re,SD,Em,In,Pr,Qu,St,Ap,Wl,Sn
        Names are:
                Agility, Constitution, Memory, Reasoning, Self Discipline,
                Empathy,Intuition, Presence, Quickness, Strength,
                Appearance, Willpower, Sanity
-->
<!ELEMENT stats (stat)+>

<!-- stat
        This contains the stat and bonus.  It must contain one or both of 
        name and abbr, and a bonus (racial) -->
<!ELEMENT stat ((name|abbr)+,racial)>

<!-- 
        Resistance Rolls
        
        This represents a races inate resistances
-->
<!ELEMENT rrs (rr)+>

<!-- name is the what is the resistence is against, racialbonus is the bonus
        for this race 

        Possible resistences are:
        Essence, Channeling, Mentalism,
        Essence/Mentalism, Channeling/Essence, Essence/Mentalism, Arcane
        Poison, Disease, Fear, 
        Heat, Cold

-->
<!ELEMENT rr (name,racialbonus)>

<!ELEMENT data (fixed,raceinfo)>

<!ELEMENT fixed (race)>
<!-- race
 The name of the race
-->
<!ELEMENT race (#PCDATA)>

<!ELEMENT raceinfo (exhaustionbonus,lifespan,souldeparture,recoverymultiplier,
             racetype,startinglanguages,talentpoints,hobbyranks,   
             bodydevelopment,arcane,channeling,essence,mentalism)>

<!ELEMENT exhaustionbonus (#PCDATA)>
<!ELEMENT lifespan (#PCDATA)>
<!ELEMENT souldeparture (#PCDATA)>
<!ELEMENT recoverymultiplier (#PCDATA)>
<!ELEMENT racetype (#PCDATA)>
<!ELEMENT startinglanguages (#PCDATA)>
<!ELEMENT talentpoints (#PCDATA)>
<!ELEMENT hobbyranks (#PCDATA)>
<!ELEMENT bodydevelopment (#PCDATA)>
<!ELEMENT arcane (#PCDATA)>
<!ELEMENT channeling (#PCDATA)>
<!ELEMENT essence (#PCDATA)>
<!ELEMENT mentalism (#PCDATA)>

<!ELEMENT skills (category)+>
<!ELEMENT category (name,ranks?,(skill|skillgroup)*)>
<!ELEMENT skill (name,ranks?,class?)>
<!ELEMENT skillgroup (name,class?,skill*)>


<!ELEMENT name  (#PCDATA)>
<!ELEMENT abbr (#PCDATA)>
<!ELEMENT racialbonus (#PCDATA)>
<!ELEMENT racial (#PCDATA)>
<!ELEMENT ranks (#PCDATA)>

=== nashidau/rmnebula/nebula/nebula/data/races/RMSS/Greater_Orcs.xml
<?xml version='1.0'?>

<!DOCTYPE rmssrace SYSTEM "/home/nash/work/rolemaster/XML/rmssrace/rmssrace.dtd">

<rmssrace>

	<data>
                <fixed>
                        <race>Greater Orc</race>
                </fixed>
                <raceinfo>
        		<exhaustionbonus>30</exhaustionbonus>
	        	<lifespan>50</lifespan>
		        <souldeparture>10</souldeparture>
        		<recoverymultiplier>1</recoverymultiplier>
	        	<racetype>2</racetype>
		        <startinglanguages>2</startinglanguages>
        		<talentpoints>50</talentpoints>
	        	<hobbyranks>10</hobbyranks>
		        <bodydevelopment>0&#x2022;7&#x2022;3&#x2022;2&#x2022;1</bodydevelopment>
        		<arcane>0&#x2022;6&#x2022;5&#x2022;4&#x2022;3</arcane>
	        	<channeling>0&#x2022;6&#x2022;5&#x2022;4&#x2022;3</channeling>
        		<essence>0&#x2022;5&#x2022;3&#x2022;2&#x2022;2</essence>
        		<mentalism>0&#x2022;5&#x2022;3&#x2022;2&#x2022;2</mentalism>
	        </raceinfo>
        </data>

	<stats>
		<stat>
			<abbr>Ag</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>Co</abbr>
			<racial>4</racial>
		</stat>
		<stat>
			<abbr>Me</abbr>
			<racial>-2</racial>
		</stat>
		<stat>
			<abbr>Re</abbr>
			<racial>-2</racial>
		</stat>
		<stat>
			<abbr>SD</abbr>
			<racial>-2</racial>
		</stat>
		<stat>
			<abbr>Em</abbr>
			<racial>-2</racial>
		</stat>
		<stat>
			<abbr>In</abbr>
			<racial>-2</racial>
		</stat>
		<stat>
			<abbr>Pr</abbr>
			<racial>-2</racial>
		</stat>
		<stat>
			<abbr>Qu</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>St</abbr>
			<racial>4</racial>
		</stat>
		<stat>
			<abbr>Ap</abbr>
			<racial>0</racial>
		</stat>
	</stats>
	<rrs>
		<rr>
			<name>Essence</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Channeling</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Mentalism</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Poison</name>
			<racialbonus>5</racialbonus>
		</rr>
		<rr>
			<name>Disease</name>
			<racialbonus>10</racialbonus>
		</rr>
		<rr>
			<name>Fear</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Heat</name>
			<racialbonus>30</racialbonus>
		</rr>
		<rr>
			<name>Cold</name>
			<racialbonus>30</racialbonus>
		</rr>
	</rrs>

	<skills>
		<category>
		<name>Armor &#x2022; Light</name>
		<ranks>3</ranks>
            <skill>
            <name>Soft</name>
            <ranks>1</ranks>
            </skill>
            <skill>
            <name>Rigid</name>
            <ranks>3</ranks>
            </skill>
		</category>
		<category>
		<name>Armor &#x2022; Medium</name>
		<ranks>3</ranks>
            <skill>
            <name>Chain</name>
            <ranks>3</ranks>
            </skill>
		</category>
		<category>
		<name>Athletic &#x2022; Brawn</name>
		<ranks>1</ranks>
        </category>
		<category>
		<name>Athletic &#x2022; Endurance</name>
		</category>
		<category>
		<name>Athletic &#x2022; Gymnastics</name>
		<ranks>1</ranks>
            <skill>
            <name>Climbing</name>
            <ranks>1</ranks>
            </skill>
		</category>
		<category>
		<name>Awareness &#x2022; Perceptions</name>
			<skill>
			<name>Alertness</name>
			<ranks>2</ranks>
			</skill>
		</category>
		<category>
		<name>Awareness &#x2022; Searching</name>
		<ranks>1</ranks>
		</category>
		<category>
		<name>Body Development</name>
		<ranks>3</ranks>
		</category>
        <category>
        <name>Communications</name>
	    <skillgroup>
                <name>Language Spoken</name>
                <!-- Human languages -->
                <skill><name>Common Speech</name><ranks>5</ranks></skill>
                <skill><name>Orcish</name><ranks>8</ranks></skill>
                <skill><name>Black speech</name><ranks>8</ranks></skill>
        </skillgroup>
    	<skillgroup>
                <name>Language Written</name>
                <skill><name>Common Speech</name><ranks>2</ranks></skill>
                <skill><name>Orcish</name><ranks>3</ranks></skill>
                <skill><name>Black speech</name><ranks>2</ranks></skill>
        </skillgroup>
        </category>
		<category>
		<name>Lore &#x2022; General</name>
		<ranks>1</ranks>
			<skillgroup>
	        		<name>Culture Lore (By Culture/Race)</name>
		        	<skill>
			        	<name>Greater Orcs</name>
        				<ranks>3</ranks>
	        		</skill>
		        	</skillgroup>
			        <skillgroup>
        			<name>Region Lore (By Region)</name>
	        		<skill>
                                        <!-- FIXME: this should be selected
                                        -->
		        		<name>A region</name>
			        	<ranks>3</ranks>
        			</skill>
			</skillgroup>
		</category>
		<category>
		<name>Outdoor &#x2022; Animal</name>
		<ranks>1</ranks>
			<skillgroup>
			<name>Riding (By Mount Type)</name>
			<skill>
				<name>Equine</name>
				<ranks>1</ranks>
			</skill>
			</skillgroup>
		</category>
		<category>
		<name>Outdoor &#x2022; Environmental</name>
		<ranks>2</ranks>
		</category>
		<category>
		<name>Tech/Trade &#x2022; General</name>
		<ranks>1</ranks>
		</category>
        <category>
		<name>Weapon &#x2022; 1H Concussion</name>
		<ranks>1</ranks>
			<skill>
			<name>A Weapon</name>
			<ranks>1</ranks>
			</skill>
		</category>
        <category>
		<name>Weapon &#x2022; 1H Edged</name>
		<ranks>4</ranks>
			<skill>
			<name>A Weapon</name>
			<ranks>4</ranks>
			</skill>
		</category>
        <category>
		<name>Weapon &#x2022; 2 Handed</name>
		<ranks>1</ranks>
			<skill>
			<name>A Weapon</name>
			<ranks>1</ranks>
			</skill>
		</category>
        <category>
		<name>Weapon &#x2022; Missile</name>
		<ranks>1</ranks>
			<skill>
			<name>A Weapon</name>
			<ranks>1</ranks>
			</skill>
		</category>
        <category>
		<name>Weapon &#x2022; Pole Arms</name>
		<ranks>1</ranks>
			<skill>
			<name>A Weapon</name>
			<ranks>1</ranks>
			</skill>
		</category>
        <category>
		<name>Weapon &#x2022; Thrown</name>
		<ranks>1</ranks>
			<skill>
			<name>A Weapon</name>
			<ranks>1</ranks>
			</skill>
		</category>
	</skills>

    <choices>
            <choice>
                    <title>Select Languages</title>
                    <multiple />
                    <ranks>4</ranks>
                    <group>Communications</group>
                    <!-- Fixme: Shoudl list specific languages -->
            </choice>
    </choices>
</rmssrace>

=== nashidau/rmnebula/nebula/nebula/data/races/RMSS/Urban_Men.xml
<?xml version='1.0'?>

<!DOCTYPE rmssrace SYSTEM "/home/nash/work/rolemaster/XML/rmssrace/rmssrace.dtd">


<rmssrace>

	<data>
                <fixed>
                        <race>Urban man</race>
                </fixed>
                <raceinfo>
        		<exhaustionbonus>0</exhaustionbonus>
	        	<lifespan>65-85</lifespan>
		        <souldeparture>10</souldeparture>
        		<recoverymultiplier>1</recoverymultiplier>
	        	<racetype>2</racetype>
		        <startinglanguages>2</startinglanguages>
        		<talentpoints>50</talentpoints>
	        	<hobbyranks>12</hobbyranks>
		        <bodydevelopment>0&#x2022;6&#x2022;4&#x2022;2&#x2022;1</bodydevelopment>
        		<arcane>0&#x2022;6&#x2022;5&#x2022;4&#x2022;3</arcane>
	        	<channeling>0&#x2022;6&#x2022;5&#x2022;4&#x2022;3</channeling>
		        <essence>0&#x2022;6&#x2022;5&#x2022;4&#x2022;3</essence>
        		<mentalism>0&#x2022;7&#x2022;6&#x2022;5&#x2022;4</mentalism>
	        </raceinfo>
        </data>

	<stats>
		<stat>
			<abbr>Ag</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>Co</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>Me</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>Re</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>SD</abbr>
			<racial>2</racial>
		</stat>
		<stat>
			<abbr>Em</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>In</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>Pr</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>Qu</abbr>
			<racial>0</racial>
		</stat>
		<stat>
			<abbr>St</abbr>
			<racial>2</racial>
		</stat>
		<stat>
			<abbr>Ap</abbr>
			<racial>0</racial>
		</stat>
	</stats>
	<rrs>
		<rr>
			<name>Essence</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Channeling</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Mentalism</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Poison</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Disease</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Fear</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Heat</name>
			<racialbonus>0</racialbonus>
		</rr>
		<rr>
			<name>Cold</name>
			<racialbonus>0</racialbonus>
		</rr>
	</rrs>

	<skills>
		<category>
		<name>Armor &#x2022; Light</name>
		<ranks>1</ranks>
		</category>
		<category>
		<name>Athletic &#x2022; Brawn</name>
		<ranks>1</ranks>
		</category>
		<category>
		<name>Athletic &#x2022; Endurance</name>
		<ranks>1</ranks>
            <skill>
            <name>Swimming</name>
            <ranks>1</ranks>
            </skill>
		</category>
		<category>
		<name>Athletic &#x2022; Gymnastics</name>
		<ranks>1</ranks>
		</category>
		<category>
		<name>Awareness &#x2022; Perceptions</name>
			<skill>
			<name>Alertness</name>
			<ranks>2</ranks>
			</skill>
		</category>
		<category>
		<name>Awareness &#x2022; Searching</name>
		<ranks>1</ranks>
		</category>
		<category>
		<name>Body Development</name>
		<ranks>1</ranks>
		</category>
		<category>
		<name>Communications</name>
		<ranks>3</ranks>
	    <skillgroup>
                <name>Language Spoken</name>
                <skill><name>Common Speech</name><ranks>8</ranks></skill>
        </skillgroup>
    	<skillgroup>
                <name>Language Written</name>
                <skill><name>Common Speech</name><ranks>4</ranks></skill>
        </skillgroup>
		</category>
		<category>
		<name>Lore &#x2022; General</name>
		<ranks>3</ranks>
			<skillgroup>
			<name>Culture Lore (By Culture/Race)</name>
			<skill>
				<name>Common men</name>
				<ranks>3</ranks>
			</skill>
			</skillgroup>
			<skillgroup>
			<name>Region Lore (By Region)</name>
			<skill>
				<name>A region</name>
				<ranks>3</ranks>
			</skill>
			</skillgroup>
		</category>
		<category>
		<name>Outdoor &#x2022; Environmental</name>
		<ranks>1</ranks>
		</category>
        <category>
        <name>Power Awareness</name>
        <ranks>2</ranks>
        </category>
        <category>
        <name>Science/Analytic &#x2022; Basic</name>
        <ranks>1</ranks>
        </category>
        <category>
        <name>Spells &#x2022; Own Realm</name>
            <skill>
            <name>One spell list</name>
            <ranks>2</ranks>
            </skill>
        </category>
		<category>
		<name>Tech/Trade &#x2022; General</name>
		<ranks>1</ranks>
		</category>
        <category>
                <name>Urban</name>
                <ranks>5</ranks>
        </category>
        <category>
		<name>Weapon &#x2022; 1H Edged</name>
		<ranks>1</ranks>
			<skill>
			<name>A Weapon</name>
			<ranks>1</ranks>
			</skill>
		</category>
		<category>
		<name>Weapon &#x2022; Missile</name>
		<ranks>1</ranks>
			<skill>
			<name>A Weapon</name>
			<ranks>1</ranks>
			</skill>
		</category>
	</skills>

        <choices>
                <choice>
                    <title>Select Languages</title>
                    <multiple />
                    <ranks>10</ranks>
                    <group>Communications</group>
                    <!-- Fixme: Should list specific languages -->
                </choice>
        </choices>
</rmssrace>
